version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: proximity_db
    environment:
      POSTGRES_DB: proximity_social
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: proximity_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: proximity_social
      DB_USER: postgres
      DB_PASSWORD: postgres
      PORT: 8080
      HOST: 0.0.0.0
      JWT_SECRET: development_secret_key_change_in_production_min_32_chars
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:

