name: proximity_backend
description: Backend server for Proximity Social app
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_web_socket: ^2.0.0
  postgres: ^3.0.5
  dart_jsonwebtoken: ^2.14.1
  crypto: ^3.0.5
  uuid: ^4.5.1
  dotenv: ^4.2.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8

